### ISSUE TITLE
User Delete Typo

### ISSUE THREAD

**Issue by Voletek** [jprjr/postgres-auth-server#1]
When attempting to delete a user from the /users page identified a typo in the button

should be a quick fix in line 9 in the following file "/opt/postgres-auth-server/lib/postgres-auth-server/views/deleteuser.etlua"
`<button type="submit" class="pure-button pure-button-primary">Delte User</button>`

**Comment by lhorace** [comment]
Fixed the typo in this PR #4

**Comment by jprjr** [comment]
Thanks!!
